### ISSUE TITLE
standardize modular

### ISSUE THREAD

**Issue by joshuahannan** [Modular-Network/ethereum-libraries#68]
## What is it?

We need to change all instances of majoolr to modular

### Problem

Our name is Modular now so Majoolr needs to go die

### Solution

find all the instances of majoolr in the libraries and change them to their appropriate title.

### Steps to implement

* Majoolr Inc changes to Modular Inc
* https://github.com/Majoolr/ changes to https://github.com/Modular-Network/ 
* majoolr.io changes to modular.network
* and mentions of majoolr or Majoolr change to modular or Modular

any other examples I don't mention should be self-explanitory. just do a: 
`grep -ri majoolr * `
in different directories to find all the instances of majoolr and ERADICATE THEM

**Comment by cylon56** [comment]
#73

**Comment by Hackdom** [comment]
Good call, I'm opening that gitter right now. Thank for the help!! That's awesome

**Comment by Hackdom** [comment]
Fixed
