### ISSUE TITLE
Owner can withdraw all ETH after the sale has completed

### ISSUE THREAD

**Issue by maurelian** [Modular-Network/ethereum-libraries#85]
## What is it?

When the sale is completed, there will be some participants whose personal valuation cap is below the total sale valuation, who have ETH left in the contract. 

The owner can unilaterally withdraw all of this ETH.

### Problem

The `withdrawOwnerEth()` function is used unmodified from the CrowdSaleLib.sol. 

https://github.com/ConsenSys/IICO_repo/blob/audits/CrowdsaleLib/IICOLib/truffle/contracts/InteractiveCrowdsaleLib.sol#L647

https://github.com/ConsenSys/IICO_repo/blob/audits/CrowdsaleLib/CrowdsaleLib.sol#L204

In a normal crowdsale, all ETH naturally belongs to the owner. That is not the case in the IICO.

**Comment by joshuahannan** [comment]
Why was this issue closed?

**Comment by maurelian** [comment]
I think I was mistaken about this issue. Upon review, it looks to me as if it only allows the withdrawal of the `ownerBalance`.

```  
uint256 amount = self.ownerBalance;
    self.ownerBalance = 0;
    self.owner.transfer(amount);
```
